# Generated by Django 5.1.5 on 2025-02-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('embedding_model', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
            ],
            options={
                'db_table': 'llm_logs',
            },
        ),
        migrations.CreateModel(
            name='MenuMappingPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.IntegerField()),
                ('menu_name', models.CharField(max_length=255)),
                ('corrected_menu_name', models.CharField(max_length=255)),
                ('master_menu_id', models.IntegerField()),
                ('master_menu_name', models.CharField(max_length=255)),
                ('eval_current', models.BooleanField(default=False)),
                ('predicted_menu_name', models.CharField(max_length=255)),
                ('eval_prediction', models.BooleanField(default=None, null=True)),
                ('response', models.TextField()),
                ('ranked_nodes', models.JSONField()),
                ('is_approved', models.BooleanField(default=None, null=True)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu_mapping.llmlogs')),
            ],
            options={
                'db_table': 'menu_mapping_predictions',
            },
        ),
    ]
