# Generated by Django 5.1.5 on 2025-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumappingprediction',
            name='quantitative_menu_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
